<?php
$_productCollection=$this->getLoadedProductCollection();
$_helper = $this->helper('catalog/output');
$_image_helper = $this->helper('catalog/image');
$store = Mage::app()->getStore();
$code  = $store->getCode();
$aspect_ratio = Mage::getStoreConfig("porto_settings/category/aspect_ratio",$code);
$ratio_width = Mage::getStoreConfig("porto_settings/category/ratio_width",$code);
$ratio_height = Mage::getStoreConfig("porto_settings/category/ratio_height",$code);

if(!$ratio_width)
    $ratio_width = 300;
if(!$ratio_height)
    $ratio_height = 400;
?>
<?php
$_coreHelper = $this->helper('core');
?>
<?php if ($_coreHelper->isModuleEnabled("Magegiant_Dailydeal")): ?>
    <script type="text/javascript">
        //<![CDATA[
        var dailydealTimeCountersCategory = new Array();
        var i = 0;
        //]]>
    </script>
<?php endif; ?>

<?php if(!$_productCollection->count()): ?>
    <div class="category-products">
        <p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
    </div>
<?php else: ?>
    <div class="category-products">
        <?php echo $this->getToolbarHtml() ?>
        <?php // List mode ?>
        <?php if($this->getMode()!='grid'): ?>
            <?php $_iterator = 0; ?>
            <ol class="products-list" id="products-list">
                <?php foreach ($_productCollection as $_product): ?>
                    <?php $product = Mage::getModel('catalog/product')->load($_product->getId()); ?>
                    <li class="item"><div class="item-area">
                            <div class="product-image-area">

                                <?php

                                $sale_label = false;


                                // Get the Special Price
                                $specialprice = $product->getFinalPrice();
                                $orgprice = $product->getPrice();
                                // Get the Special Price FROM date
                                $specialPriceFromDate = $product->getSpecialFromDate();
                                // Get the Special Price TO date
                                $specialPriceToDate = $product->getSpecialToDate();
                                // Get Current date
                                $today =  time();

                                if ($specialprice<$orgprice){
                                    $save_percent = 100-round(($specialprice/$orgprice)*100);
                                    if($today >= strtotime( $specialPriceFromDate) && $today <= strtotime($specialPriceToDate) || $today >= strtotime( $specialPriceFromDate) && is_null($specialPriceToDate)){
                                        if(Mage::getStoreConfig("porto_settings/product_label/sale", $code)){
                                            $sale_label = true;

                                            /* original porto-sale-icon # removed to show all in one box
                                             *      <div class="product-label"><span class="sale-product-icon"><?php if(Mage::getStoreConfig("porto_settings/product_label/sale_label_type", $code)):?><?php echo "-".$save_percent."%"; ?><?php else: ?><?php echo Mage::getStoreConfig("porto_settings/product_label/sale_label_text", $code);?><?php endif; ?></span></div>
                                            */
                                        }
                                    }
                                }
                                ?>
                                <?php
                                $now = date("Y-m-d");
                                $newsFrom= substr($_product->getData('news_from_date'),0,10);
                                $newsTo=  substr($_product->getData('news_to_date'),0,10);
                                if ($newsTo != '' || $newsFrom != ''){
                                    if (($newsTo != '' && $newsFrom != '' && $now>=$newsFrom && $now<=$newsTo) || ($newsTo == '' && $now >=$newsFrom) || ($newsFrom == '' && $now<=$newsTo))
                                    {
                                        if(Mage::getStoreConfig("porto_settings/product_label/new", $code)){

                                            $new_label = true; // added by @sleepz

                                            /* original porto new icon # removed to show all in one box
                                             * <div class="product-label"><span class="new-product-icon"><?php echo Mage::getStoreConfig("porto_settings/product_label/new_label_text", $code);?></span></div>
                                            */
                                        }
                                    }
                                }
                                ?>

                                <?php
                                /*
                                 * added by @sleepz:
                                 *
                                 * all labels are displayed in one box on the left side of the product box
                                 *
                                 */


                                if ($sale_label || $new_label) { // add more labels to the conditions
                                    ?>

                                    <div class="product-label-wrapper">
                                        <?php
                                        if ($sale_label) {
                                            echo '<div class="icon-percent-small"></div>';
                                        }
                                        if ($new_label) {
                                            echo '<div class="new-label"></div>';
                                        }
                                        // add more labels here...
                                        ?>
                                    </div>

                                    <?php
                                }
                                ?>


                                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
                                    <?php
                                    if(Mage::getStoreConfig("porto_settings/category/alternative_image", $code)){
                                        ?>
                                        <img id="product-collection-image-<?php echo $_product->getId(); ?>" class="defaultImage" src="<?php if($aspect_ratio):?><?php echo $_image_helper->init($_product, 'small_image')->constrainOnly(FALSE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize($ratio_width);?><?php else: ?><?php echo $_image_helper->init($_product, 'small_image')->resize($ratio_width,$ratio_height); ?><?php endif; ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"/>
                                        <img class="hoverImage" src="<?php if($aspect_ratio):?><?php echo $_image_helper->init($_product, 'thumbnail')->constrainOnly(FALSE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize($ratio_width);?><?php else: ?><?php echo $_image_helper->init($_product, 'thumbnail')->resize($ratio_width,$ratio_height); ?><?php endif; ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'thumbnail'), null, true) ?>"/>
                                        <?php
                                    } else {
                                        ?>
                                        <img id="product-collection-image-<?php echo $_product->getId(); ?>" src="<?php if($aspect_ratio):?><?php echo $_image_helper->init($_product, 'small_image')->constrainOnly(FALSE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize($ratio_width);?><?php else: ?><?php echo $_image_helper->init($_product, 'small_image')->resize($ratio_width,$ratio_height); ?><?php endif; ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"/>
                                        <?php
                                    }
                                    ?>
                                    <?php if ($_coreHelper->isModuleEnabled("Magegiant_Dailydeal")): ?>
                                        <?php
                                        if(Mage::getStoreConfig("dailydeal/general/enable", $code)){
                                            $deal = Mage::getModel('dailydeal/dailydeal')->getDealByProduct($_product->getId());

                                            if ($deal && ($deal->getQuantity() - $deal->getSold() > 0)) {
                                                ?>
                                                <?php $now = Mage::getModel('core/date')->timestamp(time()) ?>
                                                <?php $endTime = Mage::getModel('core/date')->timestamp(strtotime($deal->getCloseTime())); ?>
                                                <div class="deal-label">
                                                    <i class="icon-clock"></i>
                                                </div>
                                                <div class="bottom-product-dailydeal bottom-home-dailydeal">
                                                    <ul class="time-left">
                                                        <div class="timeleft timeleft_<?php echo $_product->getId() ?>"> </div>
                                                    </ul>
                                                </div>
                                                <script type="text/javascript">
                                                    //<![CDATA[
                                                    if(typeof dailydealTimeCountersCategory[<?php echo $deal->getId() ?>] == 'undefined'){
                                                        dailydealTimeCountersCategory[<?php echo $deal->getId() ?>] = new DailydealTimeCounter('<?php echo $now ?>', '<?php echo $endTime ?>', '<?php echo $deal->getId() ?>');
                                                        dailydealTimeCountersCategory[<?php echo $deal->getId() ?>].setTimeleft('timeleft_<?php echo $_product->getId() ?>');
                                                    }
                                                    //]]>
                                                </script>
                                                <?php
                                            }
                                        }
                                        ?>
                                    <?php endif; ?>
                                </a>
                            </div>
                            <div class="details-area">
                                <strong class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></strong>
                                <?php if(Mage::getStoreConfig("porto_settings/category/rating_star", $code)):?>
                                    <?php
                                    if (Mage::helper('catalog')->isModuleEnabled('Mage_Review')):
                                        ?>
                                        <?php
                                        $review_html = $this->getReviewsSummaryHtml($product, 'short');
                                        if($review_html){
                                            echo $review_html;
                                        }else{
                                            ?>
                                            <div class="ratings">
                                                <div class="rating-box">
                                                    <div class="rating" style="width:0"></div>
                                                </div>
                                            </div>
                                            <?php
                                        }
                                        ?>
                                    <?php endif; ?>
                                <?php endif; ?>
                                <?php
                                if ($this->getChild('name.after')) {
                                    $_nameAfterChildren = $this->getChild('name.after')->getSortedChildren();
                                    foreach ($_nameAfterChildren as $_nameAfterChildName) {
                                        $_nameAfterChild = $this->getChild('name.after')->getChild($_nameAfterChildName);	$_nameAfterChild->setProduct($_product);
                                        echo $_nameAfterChild->toHtml();
                                    }
                                }
                                ?>
                                <div class="short-desc">
                                    <?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                                </div>
                                <div class="action-area">
                                    <?php if(Mage::getStoreConfig("porto_settings/category/product_price", $code)):?>
                                        <?php echo $this->getPriceHtml($_product, true) ?>
                                    <?php endif; ?>


                                </div>
                                <div class="clearer"></div>
                            </div></li>
                <?php endforeach; ?>
            </ol>
            <script type="text/javascript">decorateList('products-list', 'none-recursive')</script>

        <?php else: ?>

        <?php // Grid Mode ?>

        <?php $_collectionSize = $_productCollection->count() ?>
        <?php $_columnCount = Mage::getStoreConfig("porto_settings/category_grid/columns",$code); ?>
            <ul class="products-grid <?php if(Mage::getStoreConfig("porto_settings/category_grid/flex_grid",$code)):?>flex-grid<?php endif; ?> columns<?php echo $_columnCount; ?><?php if(!Mage::getStoreConfig("porto_settings/category_grid/show_addtolinks", $code)):?> hide-addtolinks<?php endif; ?><?php if(!Mage::getStoreConfig("porto_settings/category_grid/show_addtocart", $code)):?> hide-addtocart<?php endif; ?><?php if(Mage::getStoreConfig("porto_settings/category_grid/move_actions", $code)):?> move-action<?php endif; ?>">
                <?php $i=0; foreach ($_productCollection as $_product): ?>
                    <?php $product = Mage::getModel('catalog/product')->load($_product->getId()); ?>
                    <li class="item"><div class="item-area">
                            <div class="product-image-area">
                                <div class="loader-container">
                                    <div class="loader">
                                        <i class="ajax-loader medium animate-spin"></i>
                                    </div>
                                </div>


                                <?php

                                $sale_label = false;
                                $new_label  = false;


                                // Get the Special Price
                                $specialprice = $product->getFinalPrice();
                                $orgprice = $product->getPrice();
                                // Get the Special Price FROM date
                                $specialPriceFromDate = $product->getSpecialFromDate();
                                // Get the Special Price TO date
                                $specialPriceToDate = $product->getSpecialToDate();
                                // Get Current date
                                $today =  time();

                                if ($specialprice<$orgprice){
                                    $save_percent = 100-round(($specialprice/$orgprice)*100);
                                    if($today >= strtotime( $specialPriceFromDate) && $today <= strtotime($specialPriceToDate) || $today >= strtotime( $specialPriceFromDate) && is_null($specialPriceToDate)){
                                        if(Mage::getStoreConfig("porto_settings/product_label/sale", $code)){
                                            $sale_label = true;

                                            /* original porto-sale-icon
                                             *      <div class="product-label"><span class="sale-product-icon"><?php if(Mage::getStoreConfig("porto_settings/product_label/sale_label_type", $code)):?><?php echo "-".$save_percent."%"; ?><?php else: ?><?php echo Mage::getStoreConfig("porto_settings/product_label/sale_label_text", $code);?><?php endif; ?></span></div>
                                            */
                                            ?>
                                            <?php
                                        }
                                    }
                                }
                                ?>
                                <?php
                                $now = date("Y-m-d");
                                $newsFrom= substr($_product->getData('news_from_date'),0,10);
                                $newsTo=  substr($_product->getData('news_to_date'),0,10);
                                if ($newsTo != '' || $newsFrom != ''){
                                    if (($newsTo != '' && $newsFrom != '' && $now>=$newsFrom && $now<=$newsTo) || ($newsTo == '' && $now >=$newsFrom) || ($newsFrom == '' && $now<=$newsTo))
                                    {
                                        if(Mage::getStoreConfig("porto_settings/product_label/new", $code)){

                                            $new_label = true; // added by @sleepz

                                            /* original porto new icon
                                             * <div class="product-label"><span class="new-product-icon"><?php echo Mage::getStoreConfig("porto_settings/product_label/new_label_text", $code);?></span></div>
                                            */
                                            ?>

                                            <?php
                                        }
                                    }
                                }
                                ?>


                                <?php
                                /*
                                 * added by @sleepz:
                                 *
                                 * all labels are displayed in one box on the left side of the product box
                                 *
                                 */


                                if ($sale_label || $new_label) { // add more labels to the conditions
                                    ?>

                                    <div class="product-label-wrapper">
                                        <?php
                                        if ($sale_label) {
                                            echo '<div class="icon-percent-small"></div>';
                                        }
                                        if ($new_label) {
                                            echo '<div class="new-label"></div>';
                                        }
                                        // add more labels here...
                                        ?>
                                    </div>

                                    <?php
                                }
                                ?>



                                <?php
                                if( Mage::getStoreConfig("quickview/general/enableview", $code) ){
                                    $base_url = $this->getUrl();
                                    if(strpos($base_url,'?')!==false)
                                        $base_url = explode("?",$this->getUrl());
                                    if(is_array($base_url))
                                        $base_url = $base_url[0];
//                        if(strpos($base_url,'index.php')!==false){
//                            $base_url = str_replace('index.php/','',$base_url);
//                            $base_url .= "index.php/quickview/index/view/";
//                        }else{
//                            $base_url .= "quickview/index/view/";
//                        }
                                    $base_url .= "quickview/index/view/";
                                    $quickview_url = $base_url."id/".$_product->getId();
                                    ?>
                                    <a href="<?php echo $quickview_url; ?>" class="quickview-icon"><span><?php echo $this->__("Schnellansicht"); ?></span><i class="icon-arrow"></i></a>
                                    <?php
                                }
                                ?>
                                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
                                    <?php
                                    if(Mage::getStoreConfig("porto_settings/category/alternative_image", $code)){
                                        ?>
                                        <img id="product-collection-image-<?php echo $_product->getId(); ?>" class="defaultImage" src="<?php if($aspect_ratio):?><?php echo $_image_helper->init($_product, 'small_image')->constrainOnly(FALSE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize($ratio_width);?><?php else: ?><?php echo $_image_helper->init($_product, 'small_image')->resize($ratio_width,$ratio_height); ?><?php endif; ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"/>
                                        <img class="hoverImage" src="<?php if($aspect_ratio):?><?php echo $_image_helper->init($_product, 'thumbnail')->constrainOnly(FALSE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize($ratio_width);?><?php else: ?><?php echo $_image_helper->init($_product, 'thumbnail')->resize($ratio_width,$ratio_height); ?><?php endif; ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'thumbnail'), null, true) ?>"/>
                                        <?php
                                    } else {
                                        ?>
                                        <img id="product-collection-image-<?php echo $_product->getId(); ?>" src="<?php if($aspect_ratio):?><?php echo $_image_helper->init($_product, 'small_image')->constrainOnly(FALSE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize($ratio_width);?><?php else: ?><?php echo $_image_helper->init($_product, 'small_image')->resize($ratio_width,$ratio_height); ?><?php endif; ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"/>
                                        <?php
                                    }
                                    ?>
                                    <?php if ($_coreHelper->isModuleEnabled("Magegiant_Dailydeal")): ?>
                                        <?php
                                        if(Mage::getStoreConfig("dailydeal/general/enable", $code)){
                                            $deal = Mage::getModel('dailydeal/dailydeal')->getDealByProduct($_product->getId());

                                            if ($deal && ($deal->getQuantity() - $deal->getSold() > 0)) {
                                                ?>
                                                <?php $now = Mage::getModel('core/date')->timestamp(time()) ?>
                                                <?php $endTime = Mage::getModel('core/date')->timestamp(strtotime($deal->getCloseTime())); ?>
                                                <div class="deal-label">
                                                    <i class="icon-clock"></i>
                                                </div>
                                                <div class="bottom-product-dailydeal bottom-home-dailydeal">
                                                    <ul class="time-left">
                                                        <div class="timeleft timeleft_<?php echo $_product->getId() ?>"> </div>
                                                    </ul>
                                                </div>
                                                <script type="text/javascript">
                                                    //<![CDATA[
                                                    if(typeof dailydealTimeCountersCategory[<?php echo $deal->getId() ?>] == 'undefined'){
                                                        dailydealTimeCountersCategory[<?php echo $deal->getId() ?>] = new DailydealTimeCounter('<?php echo $now ?>', '<?php echo $endTime ?>', '<?php echo $deal->getId() ?>');
                                                        dailydealTimeCountersCategory[<?php echo $deal->getId() ?>].setTimeleft('timeleft_<?php echo $_product->getId() ?>');
                                                    }
                                                    //]]>
                                                </script>
                                                <?php
                                            }
                                        }
                                        ?>
                                    <?php endif; ?>
                                </a>


                            </div>
                            <div class="details-area">
                                <strong class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></strong>

                                <?php
                                /*
                                 * @sleepz -> disabled the ouput of attribute-details
                                 *
                                if ($this->getChild('name.after')) {
                                    $_nameAfterChildren = $this->getChild('name.after')->getSortedChildren();
                                    foreach ($_nameAfterChildren as $_nameAfterChildName) {
                                        $_nameAfterChild = $this->getChild('name.after')->getChild($_nameAfterChildName);	$_nameAfterChild->setProduct($_product);
                                        echo $_nameAfterChild->toHtml();
                                    }
                                }
                                */
                                ?>
                                <?php if(Mage::getStoreConfig("porto_settings/category/product_price", $code)):?>
                                    <?php echo $this->getPriceHtml($_product, true) ?>
                                <?php endif; ?>


                                <?php echo '<span class="delivery-time">Verfügbarkeit größenabhängig</span>'?>




                                <?php if(Mage::getStoreConfig("porto_settings/category/rating_star", $code)):?>
                                    <?php
                                    if (Mage::helper('catalog')->isModuleEnabled('Mage_Review')):
                                        ?>
                                        <?php // only show ratings when exists
                                        $review_html = $this->getReviewsSummaryHtml($product, 'short');
                                        if($review_html){
                                            echo $review_html;
                                        }
                                        ?>
                                    <?php endif; ?>
                                <?php endif; ?>
                            </div>
                        </div></li>
                <?php endforeach ?>
            </ul>
            <script type="text/javascript">
                jQuery('.col-main .products-grid li:nth-child(2n)').addClass('nth-child-2n');
                jQuery('.col-main .products-grid li:nth-child(2n+1)').addClass('nth-child-2np1');
                jQuery('.col-main .products-grid li:nth-child(3n)').addClass('nth-child-3n');
                jQuery('.col-main .products-grid li:nth-child(3n+1)').addClass('nth-child-3np1');
                jQuery('.col-main .products-grid li:nth-child(4n)').addClass('nth-child-4n');
                jQuery('.col-main .products-grid li:nth-child(4n+1)').addClass('nth-child-4np1');
                jQuery('.col-main .products-grid li:nth-child(5n)').addClass('nth-child-5n');
                jQuery('.col-main .products-grid li:nth-child(5n+1)').addClass('nth-child-5np1');
                jQuery('.col-main .products-grid li:nth-child(6n)').addClass('nth-child-6n');
                jQuery('.col-main .products-grid li:nth-child(6n+1)').addClass('nth-child-6np1');
                jQuery('.col-main .products-grid li:nth-child(7n)').addClass('nth-child-7n');
                jQuery('.col-main .products-grid li:nth-child(7n+1)').addClass('nth-child-7np1');
                jQuery('.col-main .products-grid li:nth-child(8n)').addClass('nth-child-8n');
                jQuery('.col-main .products-grid li:nth-child(8n+1)').addClass('nth-child-8np1');
            </script>
        <?php endif; ?>
        <?php if(Mage::getStoreConfig("ajax_catalog/price_slider_settings/infinitescroll", $code)): ?>
            <div class="infinite-loader"><span class="loading"><i class="ajax-loader small animate-spin"></i><?php echo $this->__("Loading ..."); ?></span><a href="javascript:void(0)" class="btn-load-more"><?php echo $this->__("Load More ..."); ?></a></div>
        <?php endif; ?>
        <div class="toolbar-bottom">
            <?php echo $this->getToolbarHtml() ?>
        </div>
    </div>
<?php endif; ?>
<div class="swatches-js">
    <?php
    // Provides a block where additional page components may be attached, primarily good for in-page JavaScript
    if ($this->getChild('after')) {
        $_afterChildren = $this->getChild('after')->getSortedChildren();
        foreach ($_afterChildren as $_afterChildName) {
            $_afterChild = $this->getChild('after')->getChild($_afterChildName);
            //set product collection on after blocks
            $_afterChild->setProductCollection($_productCollection);
            echo $_afterChild->toHtml();
        }
    }
    ?>
</div>