<?php ?>


<section class="utility-icons">
    <a class="icon" onclick="alert('this is a todo...')">
        <div class="balloon">Hilfe</div>
        <div>Chat</div>
    </a>
    <a href="/konfigurator/" class="icon configurator">
        <div class="icon"></div>
        <div>Finder</div>
    </a>
    <a href="/showroom/" class="icon">
        <div class="marker"></div>
        <div>Filiale</div>
    </a>
    <a href="https://www.trustedshops.de/bewertung/info_XA39C17E0597670D259289CAA00EB1610.html" target="_blank" class="icon">
        <div class="trusted-shops"></div>
    </a>



</section>
