<?php /* Extensions placeholder */ ?>
<?php echo $this->getChildHtml('checkout.onepage.login.extra')?>
<div class="col2-set">
    <div class="col-1 opc-box">
        <div class="content">
            <h3><?php if( $this->getQuote()->isAllowedGuestCheckout() ): ?><?php echo $this->__('Checkout as a Guest or Register') ?><?php else: ?><?php echo $this->__('Register to Create an Account') ?><?php endif; ?></h3>
            <p>
              <?php echo $this->__('Wenn Sie in unserem Shop ein Benutzerkonto einrichten, werden Sie schneller durch den Bestellvorgang geführt, können mehrere Versandadressen speichern, Ihren bisherigen Bestellablauf verfolgen und vieles mehr.') ?>
            </p>

            <ul class="form-list" style="display:none;">
              <?php if( $this->getQuote()->isAllowedGuestCheckout() ): ?>
                <li class="control">
                  <input type="radio" name="checkout_method" id="login:guest" value="guest"<?php if($this->getQuote()->getCheckoutMethod()==Mage_Checkout_Model_Type_Onepage::METHOD_GUEST): ?> checked="checked"<?php endif; ?> class="radio" /><label for="login:guest"><?php echo $this->__('Checkout as Guest') ?></label>
                </li>
                <?php endif; ?>
                <li class="control">
                  <input type="radio" name="checkout_method" id="login:register" value="register"<?php if($this->getQuote()->getCheckoutMethod()==Mage_Checkout_Model_Type_Onepage::METHOD_REGISTER || !$this->getQuote()->isAllowedGuestCheckout()): ?> checked="checked"<?php endif ?> class="radio" /><label for="login:register"><?php echo $this->__('Register') ?></label>
                </li>
            </ul>

        </div>
        <div class="buttons-set row">
          <div class="col-md-6 left" style="text-align: left;">
            <button class="medium red" onclick="setMethodAsGuest()"><?php echo $this->__('Gastbestellung') ?> <i class="fa fa-angle-double-right"></i></button>
          </div>
          <div class="col-md-6 right">
            <button class="medium red" onclick="setMethodAsRegister()"><?php echo $this->__('Neukunde') ?> <i class="fa fa-angle-double-right"></i></button>
          </div>
        </div>
        <!-- <div class="buttons-set">
            <p class="required">&nbsp;</p>
            <button type="button" class="button" onclick="checkout.setMethod();"><span><span><?php echo ($this->getQuote()->isAllowedGuestCheckout() ? $this->__('Continue') : $this->__('Register')) ?></span></span></button>
        </div> -->
    </div>
    <div class="col-2 opc-box">
        <div class="content">
            <h3><?php echo $this->__('Login') ?></h3>
            <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
            <form id="login-form" action="<?php echo $this->getPostAction() ?>" method="post">
            <fieldset>
                <?php echo $this->getBlockHtml('formkey'); ?>
                <p>
                  <?php echo $this->__('Wenn Sie bei uns ein Benutzerkonto besitzen, melden Sie sich bitte an.') ?>
                </p>
                <ul class="form-list">
                    <li>
                        <label for="login-email" class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>
                        <div class="input-box">
                            <input type="text" class="input-text required-entry validate-email" id="login-email" name="login[username]" value="<?php echo $this->escapeHtml($this->getUsername()) ?>" />
                        </div>
                    </li>
                    <li>
                        <label for="login-password" class="required"><em>*</em><?php echo $this->__('Password') ?></label>
                        <div class="input-box">
                            <input type="password" class="input-text required-entry" id="login-password" name="login[password]" />
                        </div>
                    </li>
                    <?php echo $this->getChildHtml('form.additional.info'); ?>
                </ul>
                <a href="<?php echo $this->getUrl('customer/account/forgotpassword') ?>" class="forgot-password right"><?php echo $this->__('Forgot your password?') ?></a>
            </fieldset>
            </form>
        </div>
        <div class="buttons-set">
            <button type="submit" class="medium red right" onclick="onepageLogin(this)">
              <?php echo $this->__('Anmelden') ?> <i class="fa fa-angle-double-right"></i>
            </button>
        </div>
    </div>
    <?php echo $this->getChildHtml('login_before')?>
</div>
<script type="text/javascript">
//<![CDATA[
    var loginForm = new VarienForm('login-form', true);
    $('login-email').observe('keypress', bindLoginPost);
    $('login-password').observe('keypress', bindLoginPost);
    function bindLoginPost(evt){
        if (evt.keyCode == Event.KEY_RETURN) {
            loginForm.submit();
        }
    }
    function onepageLogin(button)
    {
        if(loginForm.validator && loginForm.validator.validate()){
            button.disabled = true;
            loginForm.submit();
        }
    }
//]]>
</script>

<script type="text/javascript">
//<![CDATA[
  function setMethodAsGuest(){
    resetMethod();
    var guest    = document.getElementById('login:guest');
    guest.setAttribute('checked', 'checked');
    checkout.setMethod();
  }

  function setMethodAsRegister(){
    resetMethod();
    var register        = document.getElementById('login:register');
    register.setAttribute('checked', 'checked');
    checkout.setMethod();
  }

  function resetMethod(){
    document.getElementById('login:register').removeAttribute('checked');
    document.getElementById('login:guest').removeAttribute('checked');
  }
//]]>
</script>
