
<form id="discount-coupon-form" action="<?php echo $this->getFormActionUrl() ?>" method="post">
  <h5><?php echo $this->__('Haben Sie einen Gutschein f&uuml;r Matratzendiscount.de?') ?></h5>
  <div class="discount-form">
      <input type="hidden" name="remove" id="remove-coupone" value="0" />
      <div class="input-box">
        <input class="input-text" id="coupon_code" name="coupon_code" value="<?php echo $this->escapeHtml($this->getCouponCode()) ?>" placeholder="Gutscheincode eingeben" />
        <button type="button" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Apply Coupon')) ?>" onclick="discountForm.submit(false)" value="<?php echo Mage::helper('core')->quoteEscape($this->__('Apply Coupon')) ?>">
          <?php echo $this->__('Einl&ouml;sen') ?>
          <?php //echo $this->__('Apply Coupon') ?>
        </button>
        <?php if(strlen($this->getCouponCode())): ?>
            <button type="button" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Cancel Coupon')) ?>" onclick="discountForm.submit(true)" value="<?php echo Mage::helper('core')->quoteEscape($this->__('Cancel Coupon')) ?>">
              <?php //echo $this->__('Cancel Coupon') ?>
              <?php echo $this->__('L&ouml;schen') ?>
            </button>
        <?php endif;?>
      </div>
  </div>
</form>
<script type="text/javascript">
//<![CDATA[
var discountForm = new VarienForm('discount-coupon-form');
discountForm.submit = function (isRemove) {
    if (isRemove) {
        $('coupon_code').removeClassName('required-entry');
        $('remove-coupone').value = "1";
    } else {
        $('coupon_code').addClassName('required-entry');
        $('remove-coupone').value = "0";
    }
    return VarienForm.prototype.submit.bind(discountForm)();
}
//]]>
</script>
