<div class="mini-cart" style="right: 125px;">
    <?php
        $store = Mage::app()->getStore();
        $code  = $store->getCode();
        $display_subtotal_price = Mage::getStoreConfig("tax/cart_display/subtotal", $code);
    ?>
    <?php $_cartQty = $this->getSummaryCount(); ?>
    <?php
        if(!$_cartQty) $_cartQty = 0;
        $quote = Mage::getSingleton('checkout/session')->getQuote();
        $items = $quote->getAllItems();
        foreach ($items as $item) {
            $priceInclVat += $item->getRowTotalInclTax();
        }
        $_subtotal = Mage::helper('checkout')->formatPrice($priceInclVat);
        // $_subtotal = $this->helper('checkout')->formatPrice(Mage::getSingleton('checkout/cart')->getQuote()->getSubtotalInclTax())
    ?>
    <a href="javascript:void(0)" class="mybag-link"><span class="cart-info"><span class="cart-qty"><?php echo $_cartQty ?></span><span><?php echo $this->__('item(s)') ?></span></span></a>
</div>
<div class="mini-cart-total" style="right: 60px;">
  <?php echo $_subtotal ?>
  <a href="#" class="mini-cart-button">&nbsp;</a>
</div>
<div class="topCartContent block-content theme-border-color">
    <div class="inner-wrapper"><?php /*extra div to smooth slideUp and slideDown*/ ?>
        <?php $_items = $this->getRecentItems() ?>
        <?php if(count($_items)): ?>
            <!-- <ol class="mini-products-list"> -->
            <table>
                <thead>
                  <th colspan="2">Artikelname</th>
                  <th>Menge</th>
                  <th>Einzelpreis</th>
                  <th>Zwischensumme</th>
                </thead>
                <tbody>
                  <?php foreach($_items as $_item): ?>
                    <?php echo $this->getItemHtml($_item) ?>
                  <?php endforeach; ?>
                </tbody>
            </table>
            <!-- </ol> -->
            <div class="totals">
                <span class="label"><strong><?php echo $this->__('Total')?></strong> <?php echo $this->__('(incl. Vat, excl. Shipping)')?>: </span>
                <span class="price-total"><?php echo $_subtotal ?></span>
            </div>
            <div class="actions">
                <a class="btn medium view-cart-button" href="<?php echo $this->getUrl('checkout/cart'); ?>">
                  <?php echo $this->__('View Cart') ?>
                  <span>(<?php echo $_cartQty . ' ' .$this->__('Products') ?>)</span>
                </a>
        <?php if($_cartQty && $this->isPossibleOnepageCheckout()): ?>
                <a class="btn orange medium" href="<?php echo $this->getCheckoutUrl(); ?>"><?php echo $this->__('Checkout') ?></a>
        <?php endif; ?>
                <div class="clearer"></div>
            </div>
        <?php else: ?>
            <p class="cart-empty">
                <?php echo $this->__('You have no items in your shopping cart.'); ?>
            </p>
        <?php endif; ?>
    </div>
</div>
<script type="text/javascript">
jQuery(function($){
  // $('.mini-cart').mouseover(function(e){
  //     $(this).children('.topCartContent').fadeIn(200);
  //     return false;
  // }).mouseleave(function(e){
  //     $(this).children('.topCartContent').fadeOut(200);
  //     return false;
  // });

  $('.mini-cart, .mini-cart-button').click(function(e){
    $('.topCartContent').toggle();
    return false;
  });
});
</script>
