<?php /** @var $this Icyapp_Solr_Block_Layer_Filter_Abstract */?>
<ol>
<?php foreach ($this->getItems() as $_item): ?>
    <li>
        <?php if ($_item->getCount()): ?>
        <?php $isSelected = $_item->getIsSelected(); ?>
          <label>
            <?php echo $_item->getName(); ?>(<?php echo $_item->getCount() ?>)
            <input type="checkbox" name="<?php echo $_item->getFilter(); ?>[<?php echo $_item->getId(); ?>]" value="<?php echo $_item->getId(); ?>" <?php echo $isSelected ? 'checked="checked"' : ''; ?> onchange="multifilter('<?php echo $_item->getFilter(); ?>','<?php echo $_item->getId(); ?>',<?php echo $isSelected ? 'true' : 'false' ?>); return false;"/>
          </label>
        <?php endif; ?>
    </li>
<?php endforeach ?>
</ol>
