<?php $_isLoginStep = (count($this->getSteps()) > 5 ) ?>
<div class="page-title" style="display: none;">
    <h1><?php echo $this->__('Checkout') ?></h1>
</div>
<script type="text/javascript" src="<?php echo $this->getJsUrl('varien/accordion.js') ?>"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/opcheckout.js') ?>"></script>

  <div class="checkout-steps-container"></div>
  <ol class="opc" id="checkoutSteps">
    <li id="opc-cart" class="cart-section">
      <div class="step-cart">
          <h2><a href="<?php echo Mage::getUrl('checkout/cart') ?>"><?php echo $this->__('Einkaufswagen') ?></a></h2>
      </div>
    </li>
    <?php if(!$_isLoginStep):?>
      <li id="opc-login" class="section">
          <div class="step-title">
              <!-- <span class="number"><?php echo $i ?></span> -->
              <h2><?php echo $this->__('Secure Connection') ?></h2>
              <a href="#"><?php echo $this->__('Edit') ?></a>
          </div>
      </li>
    <?php endif;?>
  <?php $i=0; foreach($this->getSteps() as $_stepId => $_stepInfo): ?>
  <?php if (!$this->getChild($_stepId) || !$this->getChild($_stepId)->isShow()): continue; endif; $i++ ?>
      <li id="opc-<?php echo $_stepId ?>" class="section<?php echo !empty($_stepInfo['allow'])?' allow':'' ?><?php echo !empty($_stepInfo['complete'])?' saved':'' ?>">
          <div class="step-title">
              <!-- <span class="number"><?php echo $i ?></span> -->
              <h2><?php echo ($_isLoginStep && $i == 1 ? $this->__('Secure Connection') : $_stepInfo['label']) ?></h2>
              <a href="#"><?php echo $this->__('Edit') ?></a>
          </div>
          <div id="checkout-step-<?php echo $_stepId ?>" class="step a-item" style="display:none;">
              <?php echo $this->getChildHtml($_stepId) ?>
          </div>
      </li>
  <?php endforeach ?>
  </ol>
  <script type="text/javascript">
  //<![CDATA[
      var accordion = new Accordion('checkoutSteps', '.step-title', true);
      <?php if($this->getActiveStep()): ?>
      accordion.openSection('opc-<?php echo $this->getActiveStep() ?>');
      <?php endif ?>
      var checkout = new Checkout(accordion,{
          progress: '<?php echo $this->getUrl('checkout/onepage/progress') ?>',
          review: '<?php echo $this->getUrl('checkout/onepage/review') ?>',
          saveMethod: '<?php echo $this->getUrl('checkout/onepage/saveMethod') ?>',
          failure: '<?php echo $this->getUrl('checkout/cart') ?>'}
      );
  //]]>
  </script>
<!-- </div> -->
