<?php
$_productCollection = $this->getLoadedProductCollection();
$_helper = $this->helper('catalog/output');
$_image_helper = $this->helper('catalog/image');
$store = Mage::app()->getStore();
$code = $store->getCode();
$aspect_ratio = Mage::getStoreConfig("porto_settings/category/aspect_ratio", $code);
$ratio_width = Mage::getStoreConfig("porto_settings/category/ratio_width", $code);
$ratio_height = Mage::getStoreConfig("porto_settings/category/ratio_height", $code);
if (!$ratio_width)
    $ratio_width = 300;
if (!$ratio_height)
    $ratio_height = 400;
?>
<?php
$_coreHelper = $this->helper('core');
?>
<?php if ($_coreHelper->isModuleEnabled("Magegiant_Dailydeal")): ?>
    <script type="text/javascript">
        //<![CDATA[
        var dailydealTimeCountersCategory = new Array();
        var i = 0;
        //]]>
    </script>
<?php endif; ?>

<?php if (!$_productCollection->count()): ?>
    <div class="category-products">
        <p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
    </div>
<?php else: ?>
    <div class="category-products">
        <div class="line pd-tp-10">
            <?php echo $this->getToolbarHtml() ?>
        </div>
        <?php // Grid Mode ?>

        <?php $_collectionSize = $_productCollection->count() ?>
        <?php $_columnCount = Mage::getStoreConfig("porto_settings/category_grid/columns", $code); ?>
        <ul class="products-grid <?php if (Mage::getStoreConfig("porto_settings/category_grid/flex_grid", $code)): ?>flex-grid<?php endif; ?> columns<?php echo $_columnCount; ?><?php if (!Mage::getStoreConfig("porto_settings/category_grid/show_addtolinks", $code)): ?> hide-addtolinks<?php endif; ?><?php if (!Mage::getStoreConfig("porto_settings/category_grid/show_addtocart", $code)): ?> hide-addtocart<?php endif; ?><?php if (Mage::getStoreConfig("porto_settings/category_grid/move_actions", $code)): ?> move-action<?php endif; ?>">
            <?php $i = 0;
            foreach ($_productCollection as $_product): ?>
                <?php $msrp = ($_product->getMsrp() ? intval($_product->getPrice()/$_product->getMsrp()*100) : false) ?>
                <?php $product = Mage::getModel('catalog/product')->load($_product->getId()); ?>
                <li class="item">
                    <div class="item-area">
                      <?php if($msrp): ?>
                        <div class="savings-banner">
                            -<?php echo $msrp ?> %
                        </div>
                      <?php endif; ?>
                        <div class="product-image-area">
                            <div class="loader-container">
                                <div class="loader">
                                    <i class="ajax-loader medium animate-spin"></i>
                                </div>
                            </div>
                            <?php
                            if (Mage::getStoreConfig("quickview/general/enableview", $code)) {
                                $base_url = $this->getUrl();
                                if (strpos($base_url, '?') !== false)
                                    $base_url = explode("?", $this->getUrl());
                                if (is_array($base_url))
                                    $base_url = $base_url[0];
//                        if(strpos($base_url,'index.php')!==false){
//                            $base_url = str_replace('index.php/','',$base_url);
//                            $base_url .= "index.php/quickview/index/view/";
//                        }else{
//                            $base_url .= "quickview/index/view/";
//                        }
                                $base_url .= "quickview/index/view/";
                                $quickview_url = $base_url . "id/" . $_product->getId();
                                ?>
                            <?php
                            }
                            ?>
                            <a href="<?php echo $_product->getProductUrl() ?>"
                               title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"
                               class="product-image">
                                <?php
                                if (Mage::getStoreConfig("porto_settings/category/alternative_image", $code)) {
                                    ?>
                                    <img id="product-collection-image-<?php echo $_product->getId(); ?>"
                                         class="defaultImage"
                                         src="<?php if ($aspect_ratio): ?><?php echo $_image_helper->init($_product, 'small_image')->constrainOnly(FALSE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize($ratio_width); ?><?php else: ?><?php echo $_image_helper->init($_product, 'small_image')->resize($ratio_width, $ratio_height); ?><?php endif; ?>"
                                         alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"/>
                                    <img class="hoverImage"
                                         src="<?php if ($aspect_ratio): ?><?php echo $_image_helper->init($_product, 'thumbnail')->constrainOnly(FALSE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize($ratio_width); ?><?php else: ?><?php echo $_image_helper->init($_product, 'thumbnail')->resize($ratio_width, $ratio_height); ?><?php endif; ?>"
                                         alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'thumbnail'), null, true) ?>"/>
                                <?php
                                } else {
                                    ?>
                                    <img id="product-collection-image-<?php echo $_product->getId(); ?>"
                                         src="<?php if ($aspect_ratio): ?><?php echo $_image_helper->init($_product, 'small_image')->constrainOnly(FALSE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize($ratio_width); ?><?php else: ?><?php echo $_image_helper->init($_product, 'small_image')->resize($ratio_width, $ratio_height); ?><?php endif; ?>"
                                         alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"/>
                                <?php
                                }
                                ?>
                                <?php if ($_coreHelper->isModuleEnabled("Magegiant_Dailydeal")): ?>
                                    <?php
                                    if (Mage::getStoreConfig("dailydeal/general/enable", $code)) {
                                        $deal = Mage::getModel('dailydeal/dailydeal')->getDealByProduct($_product->getId());
                                        if ($deal && ($deal->getQuantity() - $deal->getSold() > 0)) {
                                            ?>
                                            <?php $now = Mage::getModel('core/date')->timestamp(time()) ?>
                                            <?php $endTime = Mage::getModel('core/date')->timestamp(strtotime($deal->getCloseTime())); ?>
                                            <div class="deal-label">
                                                <i class="icon-clock"></i>
                                            </div>
                                            <div class="bottom-product-dailydeal bottom-home-dailydeal">
                                                <ul class="time-left">
                                                    <div
                                                        class="timeleft timeleft_<?php echo $_product->getId() ?>"></div>
                                                </ul>
                                            </div>
                                            <script type="text/javascript">
                                                //<![CDATA[
                                                if (typeof dailydealTimeCountersCategory[<?php echo $deal->getId() ?>] == 'undefined') {
                                                    dailydealTimeCountersCategory[<?php echo $deal->getId() ?>] = new DailydealTimeCounter('<?php echo $now ?>', '<?php echo $endTime ?>', '<?php echo $deal->getId() ?>');
                                                    dailydealTimeCountersCategory[<?php echo $deal->getId() ?>].setTimeleft('timeleft_<?php echo $_product->getId() ?>');
                                                }
                                                //]]>
                                            </script>
                                        <?php
                                        }
                                    }
                                    ?>
                                <?php endif; ?>
                            </a>
                            <?php
                            $sale_label = false;
                            // Get the Special Price
                            $specialprice = $product->getFinalPrice();
                            $orgprice = $product->getPrice();
                            // Get the Special Price FROM date
                            $specialPriceFromDate = $product->getSpecialFromDate();
                            // Get the Special Price TO date
                            $specialPriceToDate = $product->getSpecialToDate();
                            // Get Current date
                            $today = time();
                            if ($specialprice < $orgprice) {
                                $save_percent = 100 - round(($specialprice / $orgprice) * 100);
                                if ($today >= strtotime($specialPriceFromDate) && $today <= strtotime($specialPriceToDate) || $today >= strtotime($specialPriceFromDate) && is_null($specialPriceToDate)) {
                                    if (Mage::getStoreConfig("porto_settings/product_label/sale", $code)) {
                                        $sale_label = true;
                                        ?>
                                        <div class="product-label" style="right: 10px;"><span
                                                class="savings"><?php echo "-" . $save_percent . "%"; ?></span>
                                        </div>
                                    <?php
                                    }
                                }
                            }
                            ?>
                            <?php
                            $now = date("Y-m-d");
                            $newsFrom = substr($_product->getData('news_from_date'), 0, 10);
                            $newsTo = substr($_product->getData('news_to_date'), 0, 10);
                            if ($newsTo != '' || $newsFrom != '') {
                                if (($newsTo != '' && $newsFrom != '' && $now >= $newsFrom && $now <= $newsTo) || ($newsTo == '' && $now >= $newsFrom) || ($newsFrom == '' && $now <= $newsTo)) {
                                    if (Mage::getStoreConfig("porto_settings/product_label/new", $code)) {
                                        ?>
                                        <div class="product-label"
                                             style="right: 10px; <?php echo ($sale_label) ? "top: 40px;" : ""; ?>">
                                                <span
                                                    class="new-product-icon"><?php echo Mage::getStoreConfig("porto_settings/product_label/new_label_text", $code); ?></span>
                                        </div>
                                    <?php
                                    }
                                }
                            }
                            ?>
                        </div>
                        <div class="details-area">
                            <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>"
                                                        title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a>
                            </h2>


                            <div class="row">
                                <div class="col-md-4">
                                    <?php if (Mage::getStoreConfig("porto_settings/category/rating_star", $code)): ?>
                                        <?php
                                        if (Mage::helper('catalog')->isModuleEnabled('Mage_Review')):
                                            ?>
                                            <?php
                                            $review_html = $this->getReviewsSummaryHtml($product, 'short');
                                            if ($review_html) {
                                                echo $review_html;
                                            } else {
                                                ?>
                                                <div class="ratings" style="display: none;">
                                                    <div class="rating-box">
                                                        <div class="rating" style="width:0"></div>
                                                    </div>
                                                </div>
                                            <?php
                                            }
                                            ?>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                </div>

                                <div class="col-md-8">

                                    <?php if ($this->helper('wishlist')->isAllow()) : ?>
                                        <a href="<?php if (Mage::getStoreConfig("ajaxcart/addtolinks/enablecategory", $code)): ?>javascript:void(0)<?php else: ?><?php echo $this->helper('wishlist')->getAddUrl($_product) ?><?php endif; ?>"
                                           <?php if (Mage::getStoreConfig("ajaxcart/addtolinks/enablecategory", $code)): ?>onclick="ajaxWishlist(this,'<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>','<?php echo $_product->getId() ?>');"<?php endif; ?>
                                           class="addtowishlist"><?php echo $this->__('Wishlist') ?></a>
                                    <?php endif; ?></div>

                            </div>

                            <?php
                            if ($this->getChild('name.after')) {
                                $_nameAfterChildren = $this->getChild('name.after')->getSortedChildren();
                                foreach ($_nameAfterChildren as $_nameAfterChildName) {
                                    $_nameAfterChild = $this->getChild('name.after')->getChild($_nameAfterChildName);
                                    $_nameAfterChild->setProduct($_product);
                                    echo $_nameAfterChild->toHtml();
                                }
                            }
                            ?>
                            <?php if (Mage::getStoreConfig("porto_settings/category/product_price", $code)): ?>
                                <?php echo $this->getPriceHtml($_product, true) ?>
                            <?php endif; ?>

                            <div class="delivery-options">
                              <?php if($_product->getData('type_id') == 'configurable'): ?>
                                  <?php echo $this->__('Delivery model dependent') ?>
                              <?php else: ?>
                                  <?php if ($_product->getDelivery_time()):?>
                                      <?php echo $this->__('Delivery in') ?> <?php echo $this->htmlEscape($_product->getDelivery_time()) ?>
                                  <?php endif; ?>
                              <?php endif; ?>
                            </div>
                        </div>
                    </div>
                </li>
            <?php endforeach ?>
        </ul>
        <script type="text/javascript">
            jQuery('.col-main .products-grid li:nth-child(2n)').addClass('nth-child-2n');
            jQuery('.col-main .products-grid li:nth-child(2n+1)').addClass('nth-child-2np1');
            jQuery('.col-main .products-grid li:nth-child(3n)').addClass('nth-child-3n');
            jQuery('.col-main .products-grid li:nth-child(3n+1)').addClass('nth-child-3np1');
            jQuery('.col-main .products-grid li:nth-child(4n)').addClass('nth-child-4n');
            jQuery('.col-main .products-grid li:nth-child(4n+1)').addClass('nth-child-4np1');
            jQuery('.col-main .products-grid li:nth-child(5n)').addClass('nth-child-5n');
            jQuery('.col-main .products-grid li:nth-child(5n+1)').addClass('nth-child-5np1');
            jQuery('.col-main .products-grid li:nth-child(6n)').addClass('nth-child-6n');
            jQuery('.col-main .products-grid li:nth-child(6n+1)').addClass('nth-child-6np1');
            jQuery('.col-main .products-grid li:nth-child(7n)').addClass('nth-child-7n');
            jQuery('.col-main .products-grid li:nth-child(7n+1)').addClass('nth-child-7np1');
            jQuery('.col-main .products-grid li:nth-child(8n)').addClass('nth-child-8n');
            jQuery('.col-main .products-grid li:nth-child(8n+1)').addClass('nth-child-8np1');
        </script>
        <?php if (Mage::getStoreConfig("ajax_catalog/price_slider_settings/infinitescroll", $code)): ?>
            <div class="infinite-loader"><span class="loading"><i
                        class="ajax-loader small animate-spin"></i><?php echo $this->__("Loading ..."); ?></span><a
                    href="javascript:void(0)" class="btn-load-more"><?php echo $this->__("Load More ..."); ?></a></div>
        <?php endif; ?>

        <div class="line pd-tp-10 toolbar-bottom">
            <?php echo $this->getToolbarHtml() ?>
        </div>

    </div>
<?php endif; ?>
<div class="swatches-js">
    <?php
    // Provides a block where additional page components may be attached, primarily good for in-page JavaScript
    if ($this->getChild('after')) {
        $_afterChildren = $this->getChild('after')->getSortedChildren();
        foreach ($_afterChildren as $_afterChildName) {
            $_afterChild = $this->getChild('after')->getChild($_afterChildName);
            //set product collection on after blocks
            $_afterChild->setProductCollection($_productCollection);
            echo $_afterChild->toHtml();
        }
    }
    ?>
</div>
