<?php
$store = Mage::app()->getStore();
$code  = $store->getCode();
?>
<?php $_product = $this->getProduct(); ?>
<?php $_wishlistSubmitUrl = $this->helper('wishlist')->getAddUrl($_product); ?>

<?php if ($this->helper('wishlist')->isAllow()) : ?>
    <p><a href="<?php echo $_wishlistSubmitUrl ?>" onclick="productAddToCartForm.submitLight(this, this.href); return false;" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></p>
<?php endif; ?>
<?php
    $_compareUrl = $this->helper('catalog/product_compare')->getAddUrl($_product);
?>
<?php if(Mage::getStoreConfig("porto_settings/category/compare", $code) && $_compareUrl && false) : ?>
    <p><a href="<?php echo $_compareUrl ?>" class="link-compare"><i class="icon-compare"></i></a></p>
<?php endif; ?>
