<?php
    $_helper = $this->helper('catalog/output');
    $_product = $this->getProduct()
?>
<?php if($_additional = $this->getAdditionalData()): ?>
    <h2><?php echo $this->__('Additional Information') ?></h2>
    <dl class="data-table" id="product-attribute-specs-table">
        <?php foreach ($_additional as $_data): ?>
            <dt><?php echo $this->escapeHtml($this->__($_data['label'])) ?></dt>
            <dd><?php echo $_helper->productAttribute($_product, $_data['value'], $_data['code']) ?></dd>
        <?php endforeach; ?>
    </dl>
    <!-- <script type="text/javascript">decorateTable('product-attribute-specs-table')</script> -->
<?php endif;?>
