<?php
    $store = Mage::app()->getStore();
    $code  = $store->getCode();
?>
<form id="search_mini_form" action="<?php echo str_replace("https://","//",str_replace("http://","//",$this->helper('catalogsearch')->getResultUrl())) ?>" method="get">
    <div class="form-search <?php if(!Mage::getStoreConfig("catalogcategorysearch/general/enabled", $code)): ?>no-padding<?php endif; ?>">
        <label for="search"><?php echo $this->__('Search:') ?></label>
        <?php $categorySearchHelper = $this->helper('catalogcategorysearch'); ?>
        <input id="search" type="text" name="<?php echo $this->helper('catalogsearch')->getQueryParamName() ?>" class="input-text" />
        <button type="submit" title="<?php echo $this->__('Search') ?>" class="button"></button>
        <div id="search_autocomplete" class="search-autocomplete"></div>
        <div class="clearer"></div>
    </div>
</form>
