<h1>W&auml;hlen Sie eine Versandart</h1>
<form id="co-shipping-method-form" action="">
  <div class="opc-box">
    <div id="checkout-shipping-method-load">
       <!-- Content loaded dynamically -->
    </div>
  </div>
    <script type="text/javascript">
    //<![CDATA[
        var shippingMethod = new ShippingMethod('co-shipping-method-form', "<?php echo $this->getUrl('checkout/onepage/saveShippingMethod') ?>");
    //]]>
    </script>
    <div class="buttons-set" id="shipping-method-buttons-container">
      <a href="#" class="btn medium left" onclick="checkout.back(); return false;"><i class="fa fa-angle-double-left"></i> <?php echo $this->__('Back') ?></a>
        <button type="button" class="red medium right" onclick="shippingMethod.save()">
          <span><span><?php echo $this->__('Continue') ?> <i class="fa fa-angle-double-right"></i></span></span>
        </button>
        <span id="shipping-method-please-wait" class="please-wait" style="display:none;">
            <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo Mage::helper('core')->quoteEscape($this->__('Loading next step...')) ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Loading next step...')) ?>" class="v-middle" /> <?php echo $this->__('Loading next step...') ?>
        </span>
    </div>
</form>
